# Exported from Render on 2026-07-31T23:52:16Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: catalogo-translite
      runtime: node
      repo: https://github.com/AlgonTek/catalogo-translite
      plan: free
      envVars:
      - key: NODE_ENV
        sync: false
      region: ohio
      buildCommand: bun install
      startCommand: bun run start
      autoDeployTrigger: commit
